
import os
from pathlib import Path
from django.contrib.messages import constants as message_constants

BASE_DIR = Path(__file__).resolve().parent.parent

# For collectstatic (absolute path on your PC)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


"""
Django settings for makan_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2xsed0hhrp0cpcy_fw@=^f7j*dlbp2xp-z58aoom95l2hq1_u7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
    'jazzmin',
    'notifications',
    'projectrequests',
    'sessions_app',
    'users',
    'airequests',
    'category',
    'engineers',
    'files',
    'models3d',
    'payments',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'makan_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "makan_project" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'makan_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


ZOOM_ACCOUNT_ID = "2g0_yCiTTZysfH_Aza6HZw"
ZOOM_CLIENT_ID = "baFfAOAHR_Cp_h0m8rfcDw"
ZOOM_CLIENT_SECRET = "Ee1HtbHpkir3m0E6D4zIe1RsJD3tWbKE"
ZOOM_BASE_URL = "https://api.zoom.us/v2"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'makan_project',
        'USER': 'root',           
        'PASSWORD': 'root', 
        'HOST': 'localhost',       
        'PORT': '3306',   
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "🌌 Makan Admin Space",
    "site_header": "Makan Admin Panel",
    "site_brand": "Makan",
    "welcome_sign": "Welcome back, Galactic Admin! 🌠",
    "copyright": "Makan © 2025",
    "search_model": "users.User",
    "show_ui_builder": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Docs", "url": "https://docs.makan.com", "new_window": True},
        {"name": "Support", "url": "/admin/support/", "permissions": ["auth.view_user"]},
    ],
    "icons": {
        "auth": "fas fa-user-shield",
        "users": "fas fa-user-astronaut",
        "engineers": "fas fa-hard-hat",
        "category": "fas fa-layer-group",
        "airequests": "fas fa-robot",
        "files": "fas fa-file-invoice",
        "payments": "fas fa-credit-card",
        "sessions": "fas fa-calendar-check",
    },
    "default_icon_parents": "fas fa-folder-plus",
    "default_icon_children": "fas fa-file-circle",
    "show_sidebar": True,
    "custom_css": "css/style.css",
}

JAZZMIN_UI_TWEAKS = {
    "body_fixed": True,
    "sidebar_fixed": True,
    "sidebar_scrollable": True,
    "navbar_fixed": True,
    "footer_fixed": False,
    "no_navbar_border": True,
    "brand_color": "bg-dark text-white",
    "accent": "accent-info",
    "navbar": "navbar-dark bg-dark",
    "logo_padding": "p-3",
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'error',
}