# Generated by Django 5.2.7 on 2025-10-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('meeting_link', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
                ('sessionscol', models.CharField(max_length=45)),
                ('eng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
