# Generated by Django 5.2.7 on 2025-10-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_session_created_at_session_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='old_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
