# Generated by Django 5.2.7 on 2025-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_alter_session_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='sessionscol',
        ),
        migrations.AddField(
            model_name='session',
            name='host_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
