# Generated by Django 5.2.7 on 2025-10-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0002_engineer_bio_alter_engineer_certifications_and_more'),
        ('files', '0002_file_status_alter_file_user'),
        ('users', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='users.user')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to='engineers.engineer')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file')),
            ],
            options={
                'db_table': 'project_requests',
            },
        ),
    ]
