# Generated by Django 5.2.7 on 2025-10-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectrequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='file',
        ),
    ]
