# Generated by Django 5.2.7 on 2025-10-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectrequests', '0002_remove_projectrequest_file'),
        ('sessions_app', '0005_alter_session_options_remove_session_sessionscol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_request', to='sessions_app.session'),
        ),
    ]
