# Generated by Django 5.2.7 on 2025-10-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_engineeravailability'),
        ('projectrequests', '0003_projectrequest_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='selected_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='engineers.engineeravailability'),
        ),
    ]
