# Generated by Django 5.2.7 on 2025-10-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('ai_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_image_path', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=45)),
                ('output_images_paths', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'airequestes',
            },
        ),
    ]
