# Generated by Django 5.2.7 on 2025-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
