# Generated by Django 5.2.7 on 2025-10-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airequests', '0002_airequest_status'),
        ('users', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airequest', to='users.user'),
        ),
    ]
