# Generated by Django 5.2.7 on 2025-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_status_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
