# Generated by Django 5.2.7 on 2025-10-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_path'),
        ('projectrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projectrequests.projectrequest'),
        ),
    ]
