# Generated by Django 5.2.7 on 2025-10-03 12:15

import django.db.models.deletion
import engineers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
        ('users', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='certifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='licenses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='engineers/portfolio/', validators=[engineers.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='engineers/photos/', validators=[engineers.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_profile', to='users.user'),
        ),
    ]
