# Generated by Django 5.2.7 on 2025-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_engineer_bio_alter_engineer_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='specialization',
            field=models.CharField(choices=[('architecture', 'Architecture'), ('interior', 'Interior Design'), ('civil', 'Civil Engineering'), ('mechanical', 'Mechanical Engineering')], default='architecture', max_length=50),
        ),
    ]
