# Generated by Django 5.2.7 on 2025-10-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0003_engineer_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='engineers.engineer')),
            ],
            options={
                'db_table': 'engineer_availabilities',
                'ordering': ['date', 'start_time'],
                'unique_together': {('engineer', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
