# Generated by Django 5.2.7 on 2025-10-09 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectrequests', '0001_initial'),
        ('users', '0003_user_address_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'New Project Request'), ('accepted', 'Request Accepted'), ('rejected', 'Request Rejected'), ('completed', 'Project Completed')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectrequests.projectrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
